//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBranch_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBranch_Class()
        {
            this.AspNetBranchClass_Sections = new HashSet<AspNetBranchClass_Sections>();
        }
    
        public int Id { get; set; }
        public int BranchId { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> Capacity { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetBranch AspNetBranch { get; set; }
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual AspNetSession AspNetSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBranchClass_Sections> AspNetBranchClass_Sections { get; set; }
    }
}
