//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudentAssessment
    {
        public int Id { get; set; }
        public int StudentEnrollmentId { get; set; }
        public decimal ObtainedMarks { get; set; }
        public int SubmissionStatusId { get; set; }
        public int AssessmentId { get; set; }
        public string AssessmmentSolutionFile { get; set; }
    
        public virtual AspNetAssessment AspNetAssessment { get; set; }
        public virtual AspNetStatu AspNetStatu { get; set; }
        public virtual AspNetStudent_Enrollments AspNetStudent_Enrollments { get; set; }
    }
}
