//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetEmployee()
        {
            this.AspNetAccountants = new HashSet<AspNetAccountant>();
            this.AspNetTeachers = new HashSet<AspNetTeacher>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Position { get; set; }
        public string DateAvailable { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int NationalityId { get; set; }
        public int ReligionId { get; set; }
        public int GenderId { get; set; }
        public string CellNo { get; set; }
        public string Landline { get; set; }
        public string SpouseName { get; set; }
        public string SpouseHighestDegree { get; set; }
        public string SpouseOccupation { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal MedicalAllowance { get; set; }
        public Nullable<bool> Accomodation { get; set; }
        public decimal ProvidedFund { get; set; }
        public decimal Tax { get; set; }
        public decimal EOP { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string Illness { get; set; }
        public int BranchId { get; set; }
        public string Address { get; set; }
        public string Spouse_Address { get; set; }
        public string File { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAccountant> AspNetAccountants { get; set; }
        public virtual AspNetBranch AspNetBranch { get; set; }
        public virtual AspNetGender AspNetGender { get; set; }
        public virtual AspNetNationality AspNetNationality { get; set; }
        public virtual AspNetEmployeePosition AspNetEmployeePosition { get; set; }
        public virtual AspNetReligion AspNetReligion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher> AspNetTeachers { get; set; }
    }
}
