//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBranchClass_Sections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBranchClass_Sections()
        {
            this.AspNetStudent_Enrollments = new HashSet<AspNetStudent_Enrollments>();
            this.AspNetStudent_Histories = new HashSet<AspNetStudent_Histories>();
            this.AspNetStudentSections = new HashSet<AspNetStudentSection>();
            this.AspNetTeacher_Enrollments = new HashSet<AspNetTeacher_Enrollments>();
            this.AspNetTeacher_Histories = new HashSet<AspNetTeacher_Histories>();
        }
    
        public int Id { get; set; }
        public int BranchClassId { get; set; }
        public int SectionId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetBranch_Class AspNetBranch_Class { get; set; }
        public virtual AspNetSection AspNetSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Enrollments> AspNetStudent_Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Histories> AspNetStudent_Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudentSection> AspNetStudentSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher_Enrollments> AspNetTeacher_Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher_Histories> AspNetTeacher_Histories { get; set; }
    }
}
