//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudentSection
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int BranchClassSectionId { get; set; }
    
        public virtual AspNetBranchClass_Sections AspNetBranchClass_Sections { get; set; }
        public virtual AspNetStudent AspNetStudent { get; set; }
    }
}
