//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBranch_Admins
    {
        public int Id { get; set; }
        public int BranchId { get; set; }
        public string AdminId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetBranch AspNetBranch { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
