//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBranch()
        {
            this.AspNetBranch_Admins = new HashSet<AspNetBranch_Admins>();
            this.AspNetBranch_Class = new HashSet<AspNetBranch_Class>();
            this.AspNetEmployees = new HashSet<AspNetEmployee>();
            this.AspNetStudents = new HashSet<AspNetStudent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SchoolId { get; set; }
        public string BranchPrincipalId { get; set; }
        public bool IsActive { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBranch_Admins> AspNetBranch_Admins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBranch_Class> AspNetBranch_Class { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetEmployee> AspNetEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent> AspNetStudents { get; set; }
    }
}
