//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetStudent()
        {
            this.AspNetStudent_Enrollments = new HashSet<AspNetStudent_Enrollments>();
            this.AspNetStudent_Histories = new HashSet<AspNetStudent_Histories>();
            this.AspNetStudentSections = new HashSet<AspNetStudentSection>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RollNo { get; set; }
        public string UserId { get; set; }
        public int BranchId { get; set; }
        public string Address { get; set; }
        public string File { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual AspNetBranch AspNetBranch { get; set; }
        public virtual AspNetParent AspNetParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Enrollments> AspNetStudent_Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Histories> AspNetStudent_Histories { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudentSection> AspNetStudentSections { get; set; }
    }
}
