//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTeacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetTeacher()
        {
            this.AspNetTeacher_Enrollments = new HashSet<AspNetTeacher_Enrollments>();
            this.AspNetTeacher_Histories = new HashSet<AspNetTeacher_Histories>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string RegistrationNo { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual AspNetEmployee AspNetEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher_Enrollments> AspNetTeacher_Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTeacher_Histories> AspNetTeacher_Histories { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
