//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetVirtualRole
    {
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual AspNetVirtualRole AspNetVirtualRole1 { get; set; }
        public virtual AspNetVirtualRole AspNetVirtualRole2 { get; set; }
    }
}
