//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeaEntities : DbContext
    {
        public SeaEntities()
            : base("name=SeaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetAccountant> AspNetAccountants { get; set; }
        public virtual DbSet<AspNetAssessment> AspNetAssessments { get; set; }
        public virtual DbSet<AspNetAssessmentType> AspNetAssessmentTypes { get; set; }
        public virtual DbSet<AspNetBranch_Admins> AspNetBranch_Admins { get; set; }
        public virtual DbSet<AspNetBranch_Class> AspNetBranch_Class { get; set; }
        public virtual DbSet<AspNetBranchClass_Sections> AspNetBranchClass_Sections { get; set; }
        public virtual DbSet<AspNetBranch> AspNetBranches { get; set; }
        public virtual DbSet<AspNetClass_Courses> AspNetClass_Courses { get; set; }
        public virtual DbSet<AspNetClass> AspNetClasses { get; set; }
        public virtual DbSet<AspNetCoursePackage> AspNetCoursePackages { get; set; }
        public virtual DbSet<AspNetCours> AspNetCourses { get; set; }
        public virtual DbSet<AspNetDepartment> AspNetDepartments { get; set; }
        public virtual DbSet<AspNetEmployee> AspNetEmployees { get; set; }
        public virtual DbSet<AspNetEmployeePosition> AspNetEmployeePositions { get; set; }
        public virtual DbSet<AspNetGender> AspNetGenders { get; set; }
        public virtual DbSet<AspNetLog> AspNetLogs { get; set; }
        public virtual DbSet<AspNetNationality> AspNetNationalities { get; set; }
        public virtual DbSet<AspNetPackage> AspNetPackages { get; set; }
        public virtual DbSet<AspNetParent> AspNetParents { get; set; }
        public virtual DbSet<AspNetReligion> AspNetReligions { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetSection> AspNetSections { get; set; }
        public virtual DbSet<AspNetSession> AspNetSessions { get; set; }
        public virtual DbSet<AspNetStatu> AspNetStatus { get; set; }
        public virtual DbSet<AspNetStudent_Enrollments> AspNetStudent_Enrollments { get; set; }
        public virtual DbSet<AspNetStudent_Histories> AspNetStudent_Histories { get; set; }
        public virtual DbSet<AspNetStudentAssessment> AspNetStudentAssessments { get; set; }
        public virtual DbSet<AspNetStudent> AspNetStudents { get; set; }
        public virtual DbSet<AspNetStudentSection> AspNetStudentSections { get; set; }
        public virtual DbSet<AspNetTeacher_Enrollments> AspNetTeacher_Enrollments { get; set; }
        public virtual DbSet<AspNetTeacher_Histories> AspNetTeacher_Histories { get; set; }
        public virtual DbSet<AspNetTeacher> AspNetTeachers { get; set; }
        public virtual DbSet<AspNetTerm> AspNetTerms { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetVirtualRole> AspNetVirtualRoles { get; set; }
    }
}
